// <auto-generated />
using System;
using BuffetAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuffetAPI.Migrations
{
    [DbContext(typeof(BuffetDbContext))]
    [Migration("20260309154922_AddFee")]
    partial class AddFee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuffetAPI.Models.Employee", b =>
                {
                    b.Property<string>("EmployId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EmployName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployPosition")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("EmploySdate")
                        .HasColumnType("date");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShopId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployId");

                    b.HasIndex("ShopId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("BuffetAPI.Models.Expense", b =>
                {
                    b.Property<string>("Exp_id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("Exp_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Exp_date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("Exp_time")
                        .HasColumnType("time");

                    b.HasKey("Exp_id");

                    b.ToTable("Expense");
                });

            modelBuilder.Entity("BuffetAPI.Models.Fee", b =>
                {
                    b.Property<string>("fee_id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Exp_id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("fee_date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("fee_time")
                        .HasColumnType("time");

                    b.Property<decimal?>("fee_total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("fee_id");

                    b.HasIndex("Exp_id");

                    b.ToTable("fee");
                });

            modelBuilder.Entity("BuffetAPI.Models.Income", b =>
                {
                    b.Property<string>("Income_id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Income_amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Income_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Income_description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Income_payment")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<TimeSpan?>("Income_time")
                        .HasColumnType("time");

                    b.HasKey("Income_id");

                    b.HasIndex("Income_payment");

                    b.ToTable("Income");
                });

            modelBuilder.Entity("BuffetAPI.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LineUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("BuffetAPI.Models.Package", b =>
                {
                    b.Property<string>("Package_ID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Package_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Package_Price")
                        .HasColumnType("int");

                    b.Property<string>("Service_ID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Package_ID");

                    b.HasIndex("Service_ID")
                        .IsUnique()
                        .HasFilter("[Service_ID] IS NOT NULL");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("BuffetAPI.Models.Payment", b =>
                {
                    b.Property<string>("Pay_id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Pay_amont")
                        .HasColumnType("int");

                    b.Property<string>("Pay_channel")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("Pay_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pay_forkey")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Pay_mem")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Pay_time")
                        .HasColumnType("time");

                    b.HasKey("Pay_id");

                    b.HasIndex("Pay_forkey");

                    b.HasIndex("Pay_mem");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("BuffetAPI.Models.Product", b =>
                {
                    b.Property<string>("Pro_id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Pro_category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pro_image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Pro_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Pro_price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Pro_quan")
                        .HasColumnType("int");

                    b.Property<int?>("Pro_stock")
                        .HasColumnType("int");

                    b.Property<string>("Pro_unit")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Pro_id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("BuffetAPI.Models.Promotion", b =>
                {
                    b.Property<string>("Promo_ID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Package_ID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Promo_Discount")
                        .HasColumnType("int");

                    b.Property<string>("Promo_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Promo_ID");

                    b.HasIndex("Package_ID");

                    b.ToTable("Promotion");
                });

            modelBuilder.Entity("BuffetAPI.Models.PurchaseOrder", b =>
                {
                    b.Property<string>("Po_id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Po_Buyreq")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Po_approver")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Po_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Po_employee")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Po_status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan?>("Po_time")
                        .HasColumnType("time");

                    b.HasKey("Po_id");

                    b.HasIndex("Po_employee");

                    b.ToTable("Purchase_Order");
                });

            modelBuilder.Entity("BuffetAPI.Models.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("PO_Detail_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PO_Detail_ID"));

                    b.Property<int>("Order_Qty")
                        .HasColumnType("int");

                    b.Property<string>("Po_id")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Pro_id")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Total_Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Unit_Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("PO_Detail_ID");

                    b.HasIndex("Po_id");

                    b.HasIndex("Pro_id");

                    b.ToTable("Purchase_Order_Detail");
                });

            modelBuilder.Entity("BuffetAPI.Models.PurchaseRequisition", b =>
                {
                    b.Property<string>("PR_ID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Employ_ID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("PR_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PR_Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PR_Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PR_ID");

                    b.HasIndex("Employ_ID");

                    b.ToTable("Purchase_Requisition");
                });

            modelBuilder.Entity("BuffetAPI.Models.PurchaseRequisitionDetail", b =>
                {
                    b.Property<int>("PR_Detail_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PR_Detail_ID"));

                    b.Property<string>("PR_ID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Pro_id")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Request_Qty")
                        .HasColumnType("int");

                    b.HasKey("PR_Detail_ID");

                    b.HasIndex("PR_ID");

                    b.HasIndex("Pro_id");

                    b.ToTable("Purchase_Requisition_Detail");
                });

            modelBuilder.Entity("BuffetAPI.Models.Service", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EmployId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PackageId")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly?>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<int?>("ServiceNumberPeople")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("ServiceTime")
                        .HasColumnType("time");

                    b.HasKey("ServiceId");

                    b.HasIndex("EmployId");

                    b.HasIndex("PackageId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("BuffetAPI.Models.Shop", b =>
                {
                    b.Property<string>("ShopId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ShopAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShopPhone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ShopId");

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("BuffetAPI.Models.Stock", b =>
                {
                    b.Property<string>("Stock_ID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Exp_id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Po_id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Pro_id")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("Stock_Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Stock_Qty")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Stock_Time")
                        .HasColumnType("time");

                    b.Property<string>("Transaction_Type")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Stock_ID");

                    b.HasIndex("Exp_id");

                    b.HasIndex("Po_id");

                    b.HasIndex("Pro_id");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("Menu", b =>
                {
                    b.Property<string>("MenuId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MenuImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("MenuPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MenuStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pro_id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MenuId");

                    b.HasIndex("Pro_id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("MenuPackage", b =>
                {
                    b.Property<string>("MenusMenuId")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PackagesPackage_ID")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MenusMenuId", "PackagesPackage_ID");

                    b.HasIndex("PackagesPackage_ID");

                    b.ToTable("MenuPackage");
                });

            modelBuilder.Entity("OrderDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("ItemStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MenuId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderQuantity")
                        .HasColumnType("int");

                    b.HasKey("DetailId");

                    b.HasIndex("MenuId");

                    b.HasIndex("OrderHeaderId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("OrderHeader", b =>
                {
                    b.Property<int>("OrderHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderHeaderId"));

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderTable")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<TimeOnly?>("OrderTime")
                        .HasColumnType("time");

                    b.Property<string>("ServiceId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TotalStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("OrderHeaderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderHeader");
                });

            modelBuilder.Entity("BuffetAPI.Models.Employee", b =>
                {
                    b.HasOne("BuffetAPI.Models.Shop", "Shop")
                        .WithMany("Employees")
                        .HasForeignKey("ShopId");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("BuffetAPI.Models.Fee", b =>
                {
                    b.HasOne("BuffetAPI.Models.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("Exp_id");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("BuffetAPI.Models.Income", b =>
                {
                    b.HasOne("BuffetAPI.Models.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("Income_payment");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BuffetAPI.Models.Package", b =>
                {
                    b.HasOne("BuffetAPI.Models.Service", "Service")
                        .WithOne()
                        .HasForeignKey("BuffetAPI.Models.Package", "Service_ID");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BuffetAPI.Models.Payment", b =>
                {
                    b.HasOne("BuffetAPI.Models.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("Pay_forkey");

                    b.HasOne("BuffetAPI.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("Pay_mem");

                    b.Navigation("Member");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("BuffetAPI.Models.Promotion", b =>
                {
                    b.HasOne("BuffetAPI.Models.Package", "Package")
                        .WithMany()
                        .HasForeignKey("Package_ID");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("BuffetAPI.Models.PurchaseOrder", b =>
                {
                    b.HasOne("BuffetAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Po_employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BuffetAPI.Models.PurchaseOrderDetail", b =>
                {
                    b.HasOne("BuffetAPI.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("Po_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuffetAPI.Models.Product", "Product")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("Pro_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("BuffetAPI.Models.PurchaseRequisition", b =>
                {
                    b.HasOne("BuffetAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employ_ID");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BuffetAPI.Models.PurchaseRequisitionDetail", b =>
                {
                    b.HasOne("BuffetAPI.Models.PurchaseRequisition", "PurchaseRequisition")
                        .WithMany("PurchaseRequisitionDetails")
                        .HasForeignKey("PR_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuffetAPI.Models.Product", "Product")
                        .WithMany("PurchaseRequisitionDetails")
                        .HasForeignKey("Pro_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseRequisition");
                });

            modelBuilder.Entity("BuffetAPI.Models.Service", b =>
                {
                    b.HasOne("BuffetAPI.Models.Employee", "Employ")
                        .WithMany("Services")
                        .HasForeignKey("EmployId");

                    b.HasOne("BuffetAPI.Models.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId");

                    b.Navigation("Employ");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("BuffetAPI.Models.Stock", b =>
                {
                    b.HasOne("BuffetAPI.Models.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("Exp_id");

                    b.HasOne("BuffetAPI.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("Po_id");

                    b.HasOne("BuffetAPI.Models.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("Pro_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expense");

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Menu", b =>
                {
                    b.HasOne("BuffetAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Pro_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MenuPackage", b =>
                {
                    b.HasOne("Menu", null)
                        .WithMany()
                        .HasForeignKey("MenusMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuffetAPI.Models.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesPackage_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderDetail", b =>
                {
                    b.HasOne("Menu", "Menu")
                        .WithMany("OrderDetail")
                        .HasForeignKey("MenuId");

                    b.HasOne("OrderHeader", "OrderHeader")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("OrderHeader");
                });

            modelBuilder.Entity("OrderHeader", b =>
                {
                    b.HasOne("BuffetAPI.Models.Service", null)
                        .WithMany("Orders")
                        .HasForeignKey("ServiceId");
                });

            modelBuilder.Entity("BuffetAPI.Models.Employee", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("BuffetAPI.Models.Product", b =>
                {
                    b.Navigation("PurchaseOrderDetails");

                    b.Navigation("PurchaseRequisitionDetails");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("BuffetAPI.Models.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderDetails");
                });

            modelBuilder.Entity("BuffetAPI.Models.PurchaseRequisition", b =>
                {
                    b.Navigation("PurchaseRequisitionDetails");
                });

            modelBuilder.Entity("BuffetAPI.Models.Service", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BuffetAPI.Models.Shop", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Menu", b =>
                {
                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("OrderHeader", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
